name: autoupdate
on:
  # This will trigger on all pushes to all branches.
  push:
    branches:
      - "develop"

jobs:
  autoupdate:
    name: Auto Update
    runs-on: ubuntu-22.04
    steps:
      - uses: chinthakagodawita/autoupdate@v1.7.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "true"
          PR_READY_STATE: "ready_for_review"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          MERGE_CONFLICT_ACTION: "fail"
